CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(255),
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP NOT NULL,
    LAST_LOGIN TIMESTAMP NOT NULL,
    ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE PHONES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER VARCHAR(20) NOT NULL,
    CITY_CODE VARCHAR(10) NOT NULL,
    COUNTRY_CODE VARCHAR(10) NOT NULL,
    USER_ID BIGINT NOT NULL,
    constraint fk_user foreign key (user_id) references users(id)
);

